### ISSUE TITLE
Ways to make calledWith() use deep equality

### ISSUE THREAD

**Issue by jessepinho** [EndangeredMassa/bond#37]
Currently, tests fail when passing an object/array literal to `calledWith()`, since JavaScript compares object equality based on identity. That is, the following test will fail:

```CoffeeScript
spy = bond()
spy(foo: "bar")
expect spy.calledWith(foo: "bar")
```

The workaround I've had to use is via Underscore's `isEqual()`:

```CoffeeScript
spy = bond()
spy(foo: "bar")
expect _.isEqual(spy.calledArgs[0], foo: "bar")
```

This works, but then I don't get to use the more semantic `calledWith()`. 

Two ideas: 
- Include Underscore, and rewrite `calledWith()` as such:
```CoffeeScript
  spy.calledWith = (args...) ->
    return false if !spy.called
    lastArgs = spy.calledArgs[spy.called-1]
    _.isEqual(args, lastArgs) # And remove the arrayEqual() function lower down in bond.coffee
```
- Allow an equality-checking callback to be passed in to `calledWith()`, allowing the client to pass in `_.isEqual`, for instance.

Option 1 adds some heft to the library. But in a testing context, I'm less concerned. (Also, it'd allow you to use [`_.find`](http://underscorejs.org/#find), which would allow for a more elegant solution to #36.) Option 2 would force users to pass arguments into `calledWith` as an array, so that the second argument could always be the callback, which seems a bit clunky.

Thoughts?

**Comment by jessepinho** [comment]
Happy to do a PR for either solution, by the way.

**Comment by EndangeredMassa** [comment]
I've resisted adding any dependency to bond for quite some time. The package situation in JavaScript has long been rough. If we're going to include any dependencies, I think it makes sense to decide on a package system (probably just npm) and make a major version bump.

Is there a way to reasonably accommodate this use case without an external dependency?

**Comment by EndangeredMassa** [comment]
closing for PR: https://github.com/EndangeredMassa/bond/pull/38
